// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

type Client struct {
	ID      uuid.UUID       `json:"id"`
	Name    string          `json:"name"`
	Balance decimal.Decimal `json:"balance"`
}
